# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: R
sudo: required
warnings_are_errors: false

env:
  global:
    - CRAN: http://cran.rstudio.com

r_packages:
  - covr

after_success:
  - Rscript -e 'covr::codecov()'

after_failure:
  - cat ~/build/jtbates/kliqfindr/kliqfindr.Rcheck/00install.out
  - cat ~/build/jtbates/kliqfindr/kliqfindr.Rcheck/00check.log
